llm:
  openai:
    model: "gpt-3.5-turbo"
    base_url: "https://api.openai-proxy.org/v1"
    api_key: ""

langfuse:
  host: "https://cloud.langfuse.com"
  user_id: "tian_chat"
  function_trace_name: "LLMChat"
  chat_trace_name: "FunctionCallChat"
  secret_key: ""
  public_key: ""

tool:
  weather:
    base_url: "https://restapi.amap.com/v3/weather/weatherInfo?parameters"
    api_key: "fac0ad465078da96a3ec6ba1ccc6746f"
  
  delivery:
    base_url: "https://qyexpress.market.alicloudapi.com/composite/queryexpress"
    api_key: ""

  google:
    api_key: ""

rag:
  embedding:
    # 选择以下方式进行embedding，如果有需要修改的请修改choose字段
    choose: "default"
    
    openai:
      model: ""
      base_url: ""
      api_key: ""
    
    default:
      model: "BAAI/bge-large-zh-v1.5"
      cache_dir: r"D:\llm"
  
  rerank:
    # 选择以下方式进行rerank，如果有需要修改的请修改choose字段
    choose: "default"
    
    cohere:
      api_key: ""

    default:
      model: "BAAI/bge-reranker-large"
      cache_dir: r"D:\llm"
